#!/bin/bash
# -*- coding: utf-8 -*-
#
# @name_enUS '' 
# @name_zhTW '安裝 Deluge BT 下載軟體'
# @desc_enUS ''
# @desc_zhTW 'Linux 下相當好用的 BT 下載軟體，滿足你的 P2P 下載需求。'
# @category 'Networking'
# @maintaner '張君平 Chun-Ping Chang (mrmoneyc) <moneyc.net -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @openSUSE 
# @platform 'i386 AMD64'

echo
echo '[1;33;41m 安裝 Deluge... [m'
echo

zypper --non-interactive --no-refresh install deluge
