#!/bin/sh
# -*- coding: utf-8 -*-
#
# @name_enUS '' 
# @name_zhTW '安裝 Firefox 的 Flash 外掛'
# @desc_enUS ''
# @desc_zhTW '讓 Firefox/Iceweasel 可以正常顯示 Flash 動畫'
# @category 'Networking'
# @maintaner '張君平 Chun-Ping Chang (mrmoneyc) <moneyc.net -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @opensuse
# @platform 'i386 AMD64'
# @child 'Multimedia/multimedia-repos'

echo "正在安裝 Flash..."
zypper -n install flash-player libflashsupport pullin-flash-player 
