#!/bin/bash
# -*- coding: utf-8 -*-
#
# @name_enUS '' 
# @name_zhTW '安裝 PCMan X GTK+2 BBS 連線軟體'
# @desc_enUS ''
# @desc_zhTW 'Windows 下知名 BBS 連線軟體 PCMan 的 Linux 版本
#             愛上 BBS 的宅男宅女和 Ptt 鄉民必備！'
# @category 'Networking'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @debian ''
# @ubuntu ''
# @platform 'i386 AMD64'

case "$PLAT_NAME" in
i686|i386)
	zypper -n install http://download.opensuse.org/repositories/home:/swyear/openSUSE_11.1/i586/pcmanx-gtk2-0.svn464-23.1.i586.rpm
;;
x86_64)
	zypper -n install http://download.opensuse.org/repositories/home:/swyear/openSUSE_11.1/x86_64/pcmanx-gtk2-0.svn464-23.1.x86_64.rpm
;;
*)
	echo "PCMan X GTK+2 目前尚未支援 $PLAT_NAME 硬體架構，取消安裝。"
;;
esac

if [ -a "$REAL_HOME/.pcmanx/pcmanx" ]; then
    sed -i -e 's/\(WebBrowser=\)mozilla %s/\1xdg-open %s/' "$REAL_HOME/.pcmanx/pcmanx"
    sed -i -e 's/\(MailClient=\)mozilla %s/\1xdg-email %s/' "$REAL_HOME/.pcmanx/pcmanx"
else
    sudo -u "$REAL_USER" mkdir -p "$REAL_HOME/.pcmanx"
    sudo -u "$REAL_USER" cp scripts/files/pcmanx "$REAL_HOME/.pcmanx"
fi

