#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright (C) 2007 洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
# Copyright (C) 2008 林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>
# Copyright (C) 2009 張君平 Chun-Ping Chang (mrmoneyc) <moneyc.net -AT- gmail.com>
# Last Modified: 28 Apr 2009
# Released under GNU General Public License
# Download and install swiftfox.
# Please run as root.
#
# @name_enUS '' 
# @name_zhTW '安裝 SwiftFox - 非官方最佳化版的 Firefox'
# @desc_enUS ''
# @desc_zhTW '針對各種不同 CPU 最佳化編譯的 Firefox，效能勝過 Firefox 官方版本'
# @category 'Networking'
# @maintaner '張君平 Chun-Ping Chang (mrmoneyc) <moneyc.net -AT- gmail.com>'
# @author '洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>'
# @license 'GPL'
# @opensuse ''
# @platform 'i386 AMD64'
# @child 'Common/cpu-type.py'

CPU=`./cpu-type.py`

echo "自動偵測這台電腦上的 CPU 架構：$CPU"
if [ -n "$CPU" ]; then
	mkdir -p ./temp/swiftfox
	pushd ./temp/swiftfox
	case $CPU in
		'prescott')
			$WGET 'http://getswiftfox.com/builds/installer/prescott/install-swiftfox.sh'
			chmod a+x install-swiftfox.sh
			./install-swiftfox.sh
			popd
			rm -rf ./temp/
		;;
		'pentium-m'|'pentium3'|'pentium4'|'athlon-64-32bit')
			$WGET 'http://getswiftfox.com/builds/installer/i686/install-swiftfox.sh'
			chmod a+x install-swiftfox.sh
			./install-swiftfox.sh
			popd
			rm -rf ./temp/
		;;
		#FIXME: I am not sure AMD64 CPU's name of type
		'athlon-xp')
			$WGET 'http://getswiftfox.com/builds/installer/athlon64/install-swiftfox.sh'
			chmod a+x install-swiftfox.sh
			./install-swiftfox.sh
			popd
			rm -rf ./temp/
		;;
		*)
			echo '未知的 CPU，無法安裝 Swiftfox'
		;;
	esac

		echo "下載與處理繁體中文介面"
		SFVERSION=`cut -d / -f 3 swiftfox-rel-arch-file`
		wget http://releases.mozilla.org/pub/mozilla.org/firefox/releases/$SFVERSION/linux-i686/xpi/zh-TW.xpi
		#unzip -o zh-TW.xpi -d $HOME/swiftfox/
		#mv $HOME/swiftfox/chrome.manifest #$HOME/swiftfox/chrome/zh-TW.manifest
		#上面這3個步驟不確定是正確的，可能造成無法開啟 swiftfox
	#改成較保守的方法：第一次啟動 swiftfox 安裝繁體中文介面
	sed 's/"general.useragent.locale", "en-US"/"general.useragent.locale", "zh-TW"/' \
	$HOME/swiftfox/defaults/pref/firefox-l10n.js > $HOME/swiftfox/defaults/pref/firefox-l10n.js.tmp
	mv $HOME/swiftfox/defaults/pref/firefox-l10n.js.tmp $HOME/swiftfox/defaults/pref/firefox-l10n.js
	#上面這個步驟相當於從 about:config 來改 general.useragent.locale 為 zh-TW
	echo "處理路徑"
	ln -s $HOME/swiftfox/swiftfox $HOME/bin
	echo "處理 plugins"
	test ! -e $HOME/.mozilla/plugins && mkdir $HOME/.mozilla/plugins
	cp $HOME/swiftfox/plugins/* $HOME/.mozilla/plugins
	rm -r $HOME/swiftfox/plugins
	ln -s /usr/lib/browser-plugins $HOME/swiftfox/plugins
	#直接將 swiftfox/plugins 連結到 suse 瀏覽器 plugin 的預設安裝位置 
	echo "處理選單啟動圖示"
	echo "[Desktop Entry]" > swiftfox.desktop
i	echo "Encoding=UTF-8" >> swiftfox.desktop
	echo "Name=Swiftfox" >> swiftfox.desktop
	echo "Name[zh_TW]=Swiftfox 網頁瀏覽器" >> swiftfox.desktop
	echo "GenericName=Web browser" >> swiftfox.desktop
	echo "GenericName[zh_TW]=網頁瀏覽器" >> swiftfox.desktop
	echo "Comment=Web Browser" >> swiftfox.desktop
	echo "Comment[zh_TW]=網頁瀏覽器" >> swiftfox.desktop
	echo "Exec=swiftfox %u" >> swiftfox.desktop
	echo "Type=Application" >> swiftfox.desktop
	echo "Terminal=false" >> swiftfox.desktop
	echo "Categories=Application;WebBrowser" >> swiftfox.desktop
	echo "Icon=$HOME/swiftfox/icons/mozicon128.png" >> swiftfox.desktop
	test ! -e $HOME/.kde/share/applications && mkdir -p $HOME/.kde/share/applications
	cp swiftfox.desktop $HOME/.kde/share/applications
	test ! -e $HOME/.gnome2/vfolders/applications && mkdir -p $HOME/.gnome2/vfolders/applications
	cp swiftfox.desktop $HOME/.gnome2/vfolders/applications
	test ! -e $HOME/.local/share/applications && mkdir -p $HOME/.local/share/applications
	cp swiftfox.desktop $HOME/.local/share/applications
	echo "第一次啟動 swiftfox 以安裝中文介面"
	swiftfox zh-TW.xpi
	echo "Swiftfox $SFVERSION 已安裝完成！"
	else
	echo "未知的 CPU，無法自動安裝 Swiftfox ！"
	fi
